"""Web font subsets. The Chinese faces are 3-8 MB each (23 MB in all), too much for a phone on WiFi, so each gets a WOFF2
subset: GB2312 level 1 (the 3755 everyday characters) plus every character the app's own text, leaflets and library
use. web/fonts/sub/fonts.css declares the full TTF first and the subset after it with an exact unicode-range, so the
browser fetches the subset and falls back to the full face only for a character outside it (a rare word typed in the
studio). The two ranges never overlap: the full face claims only what the subset lacks and it holds. The loading screen gets tiny faces of its own (DS LoadPhrase / DS LoadCaps) holding only its own letters."""
from __future__ import annotations

import glob
import os

from fontTools import subset

from .library import ROOT

WEB = os.path.join(ROOT, "web")
FONTS = os.path.join(WEB, "fonts")
SUB = os.path.join(FONTS, "sub")

# family -> file in web/fonts (the Latin faces are small and stay as they are, in style.css)
CJK = [
    ("DS Brand", "STXINGKA.TTF", "brand"),
    ("DS Phrase", "方正粗黑宋简体.ttf", "phrase"),
    ("DS Cjk", "HarmonyOS_Sans_SC_Bold.ttf", "cjk"),
    ("DS CjkMed", "HarmonyOS_Sans_SC_Regular.ttf", "cjkmed"),
]
# the loading screen's own faces: (family, file, out name, where its text lives)
LOADER = [
    ("DS LoadPhrase", "方正粗黑宋简体.ttf", "load-phrase"),
    ("DS LoadCaps", "DINNextLTPro-Bold.ttf", "load-caps"),
]
LOADER_SOURCES = ["web/loader.js", "web/index.html"]


def gb2312_level1() -> set[str]:
    out = set()
    for hi in range(0xB0, 0xD8):
        for lo in range(0xA1, 0xFF):
            try:
                out.add(bytes([hi, lo]).decode("gb2312"))
            except UnicodeDecodeError:
                pass
    return out


def text_chars(paths: list[str]) -> set[str]:
    out = set()
    for p in paths:
        with open(p, encoding="utf-8", errors="ignore") as f:
            out |= set(f.read())
    return out


def project_chars() -> set[str]:
    paths = [p for ext in ("js", "html") for p in glob.glob(os.path.join(WEB, "**", "*." + ext), recursive=True) if os.sep + "vendor" + os.sep not in p]
    paths += glob.glob(os.path.join(ROOT, "leaflets", "*.json")) + glob.glob(os.path.join(ROOT, "emblems", "*.json"))
    paths += [os.path.join(ROOT, d, "index.json") for d in ("terms", "posters", "backdrops") if os.path.exists(os.path.join(ROOT, d, "index.json"))]
    return text_chars(paths)


def base_chars() -> set[str]:
    s = {chr(c) for c in range(0x20, 0x7F)}
    s |= {chr(c) for c in range(0x3000, 0x3040)}             # CJK punctuation
    s |= {chr(c) for c in range(0xFF01, 0xFF5F)}             # full-width forms
    s |= set("·—–…‘’“”•°×÷←→↑↓○●◦")
    return s


def ranges(cps: list[int]) -> str:
    """U+4E00-4E05, U+4E08, ... for a sorted list of code points"""
    out, i = [], 0
    while i < len(cps):
        j = i
        while j + 1 < len(cps) and cps[j + 1] == cps[j] + 1:
            j += 1
        out.append(f"U+{cps[i]:X}" if i == j else f"U+{cps[i]:X}-{cps[j]:X}")
        i = j + 1
    return ", ".join(out)


def make_subset(src: str, dst: str, chars: set[str]) -> list[int]:
    """writes the WOFF2 subset and returns the code points it really holds (the font may lack some we asked for)"""
    opts = subset.Options()
    opts.flavor = "woff2"
    opts.layout_features = ["*"]
    opts.name_IDs = ["*"]
    opts.notdef_outline = True
    opts.hinting = False
    font = subset.load_font(src, opts)
    have = set(font.getBestCmap() or {})
    want = sorted(ord(c) for c in chars if ord(c) in have)
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=want)
    sub.subset(font)
    subset.save_font(font, dst, opts)
    return want


def build() -> None:
    os.makedirs(SUB, exist_ok=True)
    chars = gb2312_level1() | project_chars() | base_chars()
    css = ["/* generated by `python dailystamp.py fonts`: full faces first, the subsets after them win for their range */"]
    for fam, file, name in CJK:
        src, dst = os.path.join(FONTS, file), os.path.join(SUB, name + ".woff2")
        cps = make_subset(src, dst, chars)
        v = int(os.path.getmtime(dst))
        # the full face claims only what the subset lacks and it really has. The ranges must not overlap: the browser
        # loads every face whose range covers a text (and starts the next one while the first is still coming), and a
        # character no face holds must not send it off for 8 MB it can't use
        full = sorted(set(subset.load_font(src, subset.Options()).getBestCmap() or {}) - set(cps))
        css.append(f'@font-face {{ font-family: "{fam}"; src: url("../{file}"); unicode-range: {ranges(full)}; }}')
        css.append(f'@font-face {{ font-family: "{fam}"; src: url("{name}.woff2?v={v}") format("woff2"); unicode-range: {ranges(cps)}; }}')
        print(f"  {fam:12s} {os.path.getsize(src) / 1e6:5.1f} MB -> {os.path.getsize(dst) / 1e6:5.2f} MB  ({len(cps)} chars)")
    load_chars = text_chars([os.path.join(ROOT, p) for p in LOADER_SOURCES if os.path.exists(os.path.join(ROOT, p))]) | base_chars()
    for fam, file, name in LOADER:
        dst = os.path.join(SUB, name + ".woff2")
        make_subset(os.path.join(FONTS, file), dst, load_chars)
        v = int(os.path.getmtime(dst))
        css.append(f'@font-face {{ font-family: "{fam}"; src: url("{name}.woff2?v={v}") format("woff2"); font-display: block; }}')
        print(f"  {fam:12s} -> {os.path.getsize(dst) / 1e3:5.1f} KB")
    with open(os.path.join(SUB, "fonts.css"), "w", encoding="utf-8") as f:
        f.write("\n".join(css) + "\n")
    print(f"wrote {os.path.relpath(os.path.join(SUB, 'fonts.css'), ROOT)}")
